In [34]:
import numpy as np



def swap_rows(A,i,j):
    #assignment creates only a new reference to the object. You should use the “copy” method:
    temp=A[i,:].copy()
    A[i,:]=A[j,:]
    A[j,:]=temp
    return A

#function to add weighted rows.i and j are two rows and jth row is added to i.k is weight of ith row and l is weight of jth row
def add_rows_weighted(A,i,j,k,l):
    A[i,:]=k*A[i,:]
    A[i,:]+=l*A[j,:]
    return A
#function to return row number in form of an array for zero rows
def check_zero_row(A):
    temp=A.any(axis=1)
    return temp

#to avoid zero pivot and exchange rows accordingly
def pivot_exchange(A,i,identity):
    temp=np.argsort(A[:,i][i:])
    swap_rows(A,i,i+temp[len(temp)-1])
    file.write("swap rows "+str(i)+" and "+str(i+temp[len(temp)-1])+"\n")
    swap_rows(identity,i,i+temp[len(temp)-1])
    return A
    
def row_reduce(A,identity):
    
    for i in range(4):
        A[np.abs(A)<0.001]=0
        identity[np.abs(identity)<0.001]=0
        A=pivot_exchange(A,i,identity)
        if(A[i,i]!=0):
            identity=add_rows_weighted(identity,i,i,1/(A[i,i]),0)
            file.write("scale row "+str(i)+" by "+str(1.0/A[i,i])+"\n")
            A=add_rows_weighted(A,i,i,1/(A[i,i]),0)
            
            for j in range(4):
                if(i==j):
                  continue;
                file.write("add row "+str(i)+" which is multiplied by "+str(-A[j][i])+" to row "+str(j)+"\n")    
                identity=add_rows_weighted(identity,j,i,1,-A[j][i])
                A=add_rows_weighted(A,j,i,1,-A[j][i])
                
    zeroo=check_zero_row(A)
    file.write("\n")
    file.write("Zero rows are row indices belonging to false value in this array "+str(zeroo)+"\n " )

    return A

file=open("la_ass1.txt",'w')

file.write("Example 1:    "+"\n"+"\n")
A=np.array([[2,3,1,5],[1,5,1,4],[4,5,2,1],[3,2,2,1]],dtype=float)
print(A)
file.write(str(A))
file.write("\n")
file.write("\n")

identity=np.array([[1.0,0,0,0],[0,1.0,0,0],[0,0,1.0,0],[0,0,0,1.0]],dtype=float)
A=row_reduce(A,identity)
print(A)
identity[np.abs(identity)<0.001]=0
print(identity)
file.write("\n"+"Row Reduced Form is:   "+"\n"+"\n")
file.write(str(identity))


file.write(" \n Example 2:    "+"\n"+"\n")
A=np.array([[2,3,1,2],[1,5,1,4],[4,6,2,4],[3,2,2,1]],dtype=float)
print(A)
file.write(str(A))
file.write("\n")
file.write("\n")

identity=np.array([[1.0,0,0,0],[0,1.0,0,0],[0,0,1.0,0],[0,0,0,1.0]],dtype=float)
A=row_reduce(A,identity)
print(A)
identity[np.abs(identity)<0.001]=0
print(identity)
file.write("\n"+"Identity Matrix after Row Reduction  is:   "+"\n"+"\n")
file.write(str(identity))


file.write(" \n Example 3:    "+"\n"+"\n")
A=np.array([[2,3,1,5],[1,5,1,4],[1,1,3,4],[3,2,2,1]],dtype=float)
print(A)
file.write(str(A))
file.write("\n")
file.write("\n")

identity=np.array([[1.0,0,0,0],[0,1.0,0,0],[0,0,1.0,0],[0,0,0,1.0]],dtype=float)
A=row_reduce(A,identity)
print(A)
identity[np.abs(identity)<0.001]=0
print(identity)
file.write("\n"+"Identity Matrix after Row Reduction  is:   "+"\n"+"\n")
file.write(str(identity))


file.write(" \n Example 4:    "+"\n"+"\n")
A=np.array([[2,3,1,5],[1,5,1,4],[1,2,3,4],[3,2,2,1]],dtype=float)
print(A)
file.write(str(A))
file.write("\n")
file.write("\n")

identity=np.array([[1.0,0,0,0],[0,1.0,0,0],[0,0,1.0,0],[0,0,0,1.0]],dtype=float)
A=row_reduce(A,identity)
print(A)
identity[np.abs(identity)<0.001]=0
print(identity)
file.write("\n"+"Identity Matrix after Row Reduction  is:   "+"\n"+"\n")
file.write(str(identity))

file.close()


[[ 2.  3.  1.  5.]
 [ 1.  5.  1.  4.]
 [ 4.  5.  2.  1.]
 [ 3.  2.  2.  1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 0.45652174 -0.58695652  0.47826087 -0.41304348]
 [-0.15217391  0.19565217  0.17391304 -0.19565217]
 [-0.65217391  0.69565217 -0.82608696  1.30434783]
 [ 0.23913043 -0.02173913 -0.13043478  0.02173913]]
[[ 2.  3.  1.  2.]
 [ 1.  5.  1.  4.]
 [ 4.  6.  2.  4.]
 [ 3.  2.  2.  1.]]
[[ 1.          0.          0.         -0.33333333]
 [ 0.          1.          0.          0.83333333]
 [ 0.          0.          1.          0.16666667]
 [ 0.          0.          0.          0.        ]]
[[ 0.         -0.66666667  0.66666667 -0.33333333]
 [ 0.          0.16666667  0.08333333 -0.16666667]
 [ 0.          0.83333333 -1.08333333  1.16666667]
 [ 1.          0.         -0.5         0.        ]]
[[ 2.  3.  1.  5.]
 [ 1.  5.  1.  4.]
 [ 1.  1.  3.  4.]
 [ 3.  2.  2.  1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
