In [29]:
import numpy as np



def swap_rows(A,i,j):
    #assignment creates only a new reference to the object. You should use the “copy” method:
    temp=A[i,:].copy()
    A[i,:]=A[j,:]
    A[j,:]=temp
    return A

#function to add weighted rows.i and j are two rows and jth row is added to i.k is weight of ith row and l is weight of jth row
def add_rows_weighted(A,i,j,k,l):
    A[i,:]=k*A[i,:]
    A[i,:]+=l*A[j,:]
    return A
#function to return row number in form of an array for zero rows
def check_zero_row(A):
    temp=A.any(axis=1)
    return temp

#to avoid zero pivot and exchange rows accordingly
def pivot_exchange(A,i,identity):
    temp=np.argsort(A[:,i][i:])
    swap_rows(A,i,i+temp[len(temp)-1])
    file.write("swap rows "+str(i)+" and "+str(i+temp[len(temp)-1])+"\n")
    swap_rows(identity,i,i+temp[len(temp)-1])
    return A
    
def row_reduce(A,identity):
    
    for i in range(4):
        A[np.abs(A)<0.001]=0
        identity[np.abs(identity)<0.001]=0
        A=pivot_exchange(A,i,identity)
        if(A[i,i]!=0):
            identity=add_rows_weighted(identity,i,i,1/(A[i,i]),0)
            file.write("scale row "+str(i)+" by "+str(1.0/A[i,i])+"\n")
            A=add_rows_weighted(A,i,i,1/(A[i,i]),0)
            
            for j in range(4):
                if(i==j):
                  continue;
                file.write("add row "+str(i)+" which is multiplied by "+str(-A[j][i])+" to row "+str(j)+"\n")    
                identity=add_rows_weighted(identity,j,i,1,-A[j][i])
                A=add_rows_weighted(A,j,i,1,-A[j][i])
                
    zeroo=check_zero_row(A)
    file.write("\n")
    file.write("Zero rows are row indices belonging to false value in this array "+str(zeroo)+"\n " )

    return A

file=open("la_ass1.txt",'w')

file.write("Example 1:    "+"\n"+"\n")
A=np.array([[2,3,1,10],[1,7,1,16],[4,5,2,1],[3,2,2,1]],dtype=float)
print(A)
file.write(str(A))
file.write("\n")
file.write("\n")

identity=np.array([[1.0,0,0,0],[0,1.0,0,0],[0,0,1.0,0],[0,0,0,1.0]],dtype=float)
A=row_reduce(A,identity)
print(A)
identity[np.abs(identity)<0.001]=0
print(identity)
file.write("\n"+"Row Reduced Form is:   "+"\n"+"\n")
file.write(str(identity))



file.close()


[[  2.   3.   1.  10.]
 [  1.   7.   1.  16.]
 [  4.   5.   2.   1.]
 [  3.   2.   2.   1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 0.73228346 -0.4488189   0.40944882 -0.5511811 ]
 [-0.24409449  0.1496063   0.19685039 -0.1496063 ]
 [-0.91338583  0.52755906 -0.77952756  1.47244094]
 [ 0.11811024 -0.00787402 -0.06299213  0.00787402]]
